### ISSUE TITLE
Add setup.py install command to install docs

### ISSUE THREAD

**Issue by rachel3834** [ebachelet/pyLIMA#16]
In the doc:
https://ebachelet.github.io/pyLIMA/Installation.html

After the line:
> python setup.py build_ext --build-lib=./pyLIMA/subroutines/VBBinaryLensingLibrary

The next command in the sequence should be 
> python setup.py install

**Comment by ebachelet** [comment]
Actually that is not true, since we are still in the "local install" mode. Then nobody should run 
python setup.py install
 but instead run 
python setup.py build_ext --build-lib=./pyLIMA/subroutines/VBBinaryLensingLibrary
and import pyLIMA with sys

HOWEVER, I just modify the code, and fix the bugs hopefully, and it looks the general pyLIMA, and unit tests, pass on a global install. So basically, users can :
python setup.py install

and then run pyLIMA without the call to the local library. If some tests can be made before, I modify docs, example etc that could be great. Especially on non LINUX machine.

**Comment by ebachelet** [comment]
I think we can close this.
