### ISSUE TITLE
Importing pyLIMA bokeh error

### ISSUE THREAD

**Issue by Vikramb1** [ebachelet/pyLIMA#52]
When I try to import pyLIMA, I get this error. I have tried downgrading bokeh but that doesn't seem to work. Any ideas on how to fix this?

When I run this:

from pyLIMA import microlsimulator, telescopes, event, microlmodels

I get the error: 

ModuleNotFoundError: No module named 'bokeh.models.markers'

**Comment by Vikramb1** [comment]
@ebachelet is there any fix to this? Or anyone else?

**Comment by ytsapras** [comment]
It is recommended that you install pyLIMA in a virtual environment so that there are no conflicts with your local python installations. (Personally, I use a new conda environment).

Did you try a new clean install of pyLIMA and you still get the same error?

If yes, which version of python, pyLIMA and which version of each of those packages are you running?

**Comment by Vikramb1** [comment]
I tried a clean install but I get a new error this time: 

ImportError: cannot import name 'Markup' from 'jinja2' (/sw/python-versions/python-3.10.8/lib/python3.10/site-packages/jinja2/__init__.py)

How do you use a new conda environment to install pyLIMA? Maybe I could try that?

For some reason, when I try and run pyLIMA.__version__, I get the error: AttributeError: module 'pyLIMA' has no attribute '__version__'.

Thanks for the help.

**Comment by rachel3834** [comment]
I've not tried to install pyLIMA into a Conda environment, but I use Python's own [virtual environment app ](https://docs.python.org/3/library/venv.html) all the time with PyLIMA and I very much recommend that approach.  
I'm sure it can be built within Conda, but Conda manages the packages a little differently and I've not had a chance to test that. 

Instead, I recommend that you create a new Python3 venv (instructions can be found at the link above), activate that venv and then follow PyLIMA's install procedure within that shell, installing the dependencies that I shared in the requirements file that I posted earlier to this thread.  That's the process I use on Unix/Mac OS and it works very well.  

I agree that PyLIMA seems to lack a clear version string, and that would be very convenient to have, so I'll create an issue for that.  In the meantime, you can use the pip freeze command to find out what version you have.

**Comment by Vikramb1** [comment]
> I've not tried to install pyLIMA into a Conda environment, but I use Python's own [virtual environment app ](https://docs.python.org/3/library/venv.html) all the time with PyLIMA and I very much recommend that approach. I'm sure it can be built within Conda, but Conda manages the packages a little differently and I've not had a chance to test that.
> 
> Instead, I recommend that you create a new Python3 venv (instructions can be found at the link above), activate that venv and then follow PyLIMA's install procedure within that shell, installing the dependencies that I shared in the requirements file that I posted earlier to this thread. That's the process I use on Unix/Mac OS and it works very well.
> 
> I agree that PyLIMA seems to lack a clear version string, and that would be very convenient to have, so I'll create an issue for that. In the meantime, you can use the pip freeze command to find out what version you have.

Got it, thanks! For reference, I seem to have fixed my problem with this by downgrading my bokeh and jinja2 versions.

**Comment by ytsapras** [comment]
@Vikramb1 That's some progress at least :) The fact that you get a different error after reinstalling it indicates that it is probably a compatibility issue between the different versions of libraries pyLIMA requires. Newer library releases are not always fully backwards compatible and until related libraries get updated, sometime issues can arise. I agree that it would probably be helpful to have specific versions of packages in the requirements.txt file, and maybe that is something @ebachelet will consider.

In order to set up a Conda environment for pyLIMA (which is how I always do it), I do the following:

`conda create -n pyLIMA python=3.9` # I use python 3.9 and call my environment pyLIMA but you may use whatever name you prefer. 

`conda activate pyLIMA` # Activate the environment

`pip install -r requirements.txt` # Now within the environment, install the pyLIMA requirements

`python setup.py install` # Finally, install pyLIMA

(Sometimes I have to do a bit of googling to resolve incompatibility issues between different packages.)

**Comment by rachel3834** [comment]
I'm glad you have been able to get PyLIMA working @Vikramb1 !  I will mark this issue as resolved, but feel free to contact us again if you have any more questions.

**Comment by Vikramb1** [comment]
> @Vikramb1 That's some progress at least :) The fact that you get a different error after reinstalling it indicates that it is probably a compatibility issue between the different versions of libraries pyLIMA requires. Newer library releases are not always fully backwards compatible and until related libraries get updated, sometime issues can arise. I agree that it would probably be helpful to have specific versions of packages in the requirements.txt file, and maybe that is something @ebachelet will consider.
> 
> In order to set up a Conda environment for pyLIMA (which is how I always do it), I do the following:
> 
> `conda create -n pyLIMA python=3.9` # I use python 3.9 and call my environment pyLIMA but you may use whatever name you prefer.
> 
> `conda activate pyLIMA` # Activate the environment
> 
> `pip install -r requirements.txt` # Now within the environment, install the pyLIMA requirements
> 
> `python setup.py install` # Finally, install pyLIMA
> 
> (Sometimes I have to do a bit of googling to resolve incompatibility issues between different packages.)

Thank you! I will use this method of installation from now on.

**Comment by Vikramb1** [comment]
> I'm glad you have been able to get PyLIMA working @Vikramb1 ! I will mark this issue as resolved, but feel free to contact us again if you have any more questions.

Yes, thank you very much.
