### ISSUE TITLE
Example 1 input data

### ISSUE THREAD

**Issue by eddiemorris135** [ebachelet/pyLIMA#55]
thanks for placing this tool in the public domain.

As a hobbyist I am using it to learn more about microlensing. However, I am struggling to find suitable data would replace 'Survey_1.dat' for example. 

I attempted to use the following database: 
https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblSearch/nph-tblSearchInit?app=ExoTbls&config=keplerstellar 
with kepler ID 11904151 

but the resulting PDCSAP_FLUX_ERR array is not of the same length as the PDCSAP_FLUX array.

Perhaps there are more convenient database sources?
Thanks
Ed

**Comment by ytsapras** [comment]
Hi Ed,
We're pleased to hear that you want to learn more about microlensing. Even though it is the third most successful method in finding exoplanets, it is a rather tricky one to explain when compared to transits or radial velocity. The effort does pay off though, once you start being able to visualize the geometry of the system in your head!

To answer your question, the easiest option is to download light curves directly from the surveys. e.g. if you want data from the OGLE 2018 survey, go to [their website](http://ogle.astrouw.edu.pl/ogle4/ews/2018/ews.html) and click on the name of any event. This will take you to the event page, where you can find a link to the actual photometry data file right at the bottom. 

Most new microlensing publications these days also include the actual light curve data as attachments to the electronic version of the article, so that's another option to keep in mind.

**Comment by eddiemorris135** [comment]
Thanks guys for the tips!
